version: '3.8'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - pw-vol-db:/var/lib/postgresql/data
    networks:
      - pw-network
networks:
  pw-network:
    driver: bridge
volumes:
  pw-vol-db:
    driver: local
